# Generated by Django 5.2.4 on 2025-09-19 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#667eea', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='admin_panel.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='admin_panel.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usergroup',
            index=models.Index(fields=['tenant', 'is_active'], name='admin_panel_tenant__0c074e_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroup',
            index=models.Index(fields=['created_by'], name='admin_panel_created_816edc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='usergroupmembership',
            index=models.Index(fields=['user', 'is_active'], name='admin_panel_user_id_133d56_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroupmembership',
            index=models.Index(fields=['group', 'is_active'], name='admin_panel_group_i_3e6ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usergroupmembership',
            unique_together={('user', 'group')},
        ),
    ]
