# Generated by Django 5.2.4 on 2025-09-13 18:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('call', 'Call'), ('remote_wipe', 'Remote Wipe'), ('key_rotation', 'Key Rotation')], max_length=20)),
                ('encrypted_payload', models.BinaryField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crypto.device')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('apns_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry')], max_length=10)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='notifications.notificationqueue')),
            ],
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['device', 'scheduled_at'], name='notificatio_device__6c7fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_bbc331_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_70a650_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['response_status'], name='notificatio_respons_ffbd58_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_d19621_idx'),
        ),
    ]
