name: securevox_app
description: SecureVOX — app mobile E2EE
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Local notifications per iOS/Android (senza Firebase)
  # flutter_local_notifications: ^16.3.3  # Temporaneamente disabilitato
  
  # Badge app icon
  # flutter_app_badger: ^1.5.0  # Temporaneamente disabilitato (discontinued)
  
  # Wake lock per mantenere schermo acceso
  # wakelock_plus: ^1.1.4  # Sostituito con screen_brightness per compatibilità
  screen_brightness: ^0.2.2+1
  
  # Overlay per notifiche sempre visibili
  # overlay_support: ^2.0.0  # Temporaneamente disabilitato per problemi iOS
  
  # Audio nativo iOS per evitare crash WebRTC su macOS
  # flutter_webrtc: ^0.10.7  # Temporaneamente disabilitato per problemi iOS
  
  # Sistema audio nativo alternativo
  # flutter_callkit_incoming: ^2.0.0  # Temporaneamente disabilitato
  
  # Crypto
  crypto: ^3.0.5
  
  # HTTP & API
  http: ^1.5.0
  http_parser: ^4.0.2
  dio: ^5.9.0
  web_socket_channel: ^3.0.3
  socket_io_client: ^3.1.2
  
  # State Management
  provider: ^6.1.1
  
  # UI & Navigation
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utils
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2
  # connectivity_plus: ^5.0.2 # Temporarily disabled due to API compatibility issues
  
  # Media & File Handling
  image_picker: ^1.2.0
  file_picker: ^8.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  image: ^4.5.4
  
  # PDF Preview
  # flutter_pdfview: ^1.3.2  # Temporaneamente disabilitato
  
  # Office Documents Preview (DOCX, XLSX, PPTX)
  webview_flutter: ^4.4.2  # Ripristinato per compatibilità
  # flutter_inappwebview: ^6.0.0  # Temporaneamente disabilitato per problemi iOS
  # flutter_html: ^3.0.0-beta.2  # Temporaneamente disabilitato per problemi iOS
  archive: ^4.0.7
  url_launcher: ^6.2.1
  mime: ^1.0.4
  
  # Audio Recording
  record: ^6.1.1
  
  # Media Players
  # audioplayers: ^5.2.1  # Temporaneamente disabilitato per risolvere errori di build
  video_player: ^2.10.0
  # chewie: ^1.7.4  # Sostituito con controller personalizzato per compatibilità
  
  # WebRTC per SecureVOX Call
  # flutter_webrtc: ^1.2.0  # Temporaneamente disabilitato per problemi iOS
  
  # Contacts - Abilitato per sviluppo
  flutter_contacts: ^1.1.9
  
  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/images/Logo01.png

# Configurazione icona app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
