# Generated by Django 5.2.4 on 2025-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatmessage_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadati del messaggio (URL immagine, caption, etc.)', null=True),
        ),
    ]
