# Generated by Django 5.2.4 on 2025-09-16 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_chatmessage_read_at_chatmessage_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_users',
            field=models.ManyToManyField(blank=True, help_text='Utenti che hanno eliminato questo messaggio (solo per loro)', to=settings.AUTH_USER_MODEL),
        ),
    ]
