# Generated by Django 5.2.4 on 2025-09-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_chatmessage_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_by_users',
            field=models.ManyToManyField(blank=True, help_text='Utenti che hanno eliminato questa chat', related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text="Quando è stata richiesta l'eliminazione", null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, help_text="Utente che ha richiesto l'eliminazione", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_chat_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='gestation_expires_at',
            field=models.DateTimeField(blank=True, help_text='Quando scade il periodo di gestazione (7 giorni)', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_in_gestation',
            field=models.BooleanField(default=False, help_text='True se la chat è in periodo di gestazione (sola lettura)'),
        ),
        migrations.AddField(
            model_name='chat',
            name='pending_deletion_notification_sent',
            field=models.BooleanField(default=False, help_text='True se la notifica di eliminazione è stata inviata'),
        ),
    ]
