# Generated by Django 5.2.4 on 2025-09-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chat_deleted_by_users_chat_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='gestation_notification_shown',
            field=models.BooleanField(default=False, help_text="True se la notifica di gestazione è già stata mostrata all'utente"),
        ),
    ]
