# Generated by Django 5.2.4 on 2025-09-18 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_gestation_notification_shown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unreachable', 'Unreachable')], default='offline', max_length=20)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('has_connection', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Status',
                'verbose_name_plural': 'User Statuses',
                'db_table': 'api_userstatus',
                'indexes': [models.Index(fields=['status'], name='api_usersta_status_9ff2cf_idx'), models.Index(fields=['is_logged_in'], name='api_usersta_is_logg_0d6396_idx'), models.Index(fields=['last_seen'], name='api_usersta_last_se_05ed92_idx'), models.Index(fields=['session_token'], name='api_usersta_session_0f72dc_idx')],
            },
        ),
    ]
