# Generated by Django 5.2.4 on 2025-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('completed', 'Completed'), ('missed', 'Missed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('seen', 'Seen')], default='completed', max_length=10),
        ),
    ]
