# Generated by Django 5.2.4 on 2025-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_call_session_id_alter_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
