# Generated by Django 5.2.4 on 2025-09-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_call_ended_at_call_is_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('connected', 'Connected'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('failed', 'Failed')], default='ringing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('encrypted_payload', models.TextField(blank=True, null=True)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_calls_received', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_calls_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebRTC Call',
                'verbose_name_plural': 'WebRTC Calls',
                'db_table': 'api_webrtc_call',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('audio_muted', models.BooleanField(default=False)),
                ('video_muted', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.webrtccall')),
            ],
            options={
                'verbose_name': 'Call Participant',
                'verbose_name_plural': 'Call Participants',
                'db_table': 'api_call_participant',
                'unique_together': {('call', 'user')},
            },
        ),
    ]
