# Generated by Django 4.2.16 on 2025-10-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_webrtccall_callparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('contact', 'Contact'), ('location', 'Location')], default='text', max_length=20),
        ),
    ]
