# Generated by Django 4.2.16 on 2025-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_contact_location_message_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='e2e_public_key',
            field=models.TextField(blank=True, help_text='Chiave pubblica Diffie-Hellman per E2EE', null=True),
        ),
    ]
