# Generated by Django 4.2.16 on 2025-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_e2e_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='e2e_enabled',
            field=models.BooleanField(default=True, help_text='E2EE abilitato per questo utente (default: True)'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='e2e_force_disabled',
            field=models.BooleanField(default=False, help_text='Admin ha forzato disabilitazione E2EE per questo utente'),
        ),
    ]
