# Generated by Django 5.2.4 on 2025-09-21 21:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nome dell'app", max_length=200)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('version', models.CharField(help_text="Versione dell'app (es. 1.0.0)", max_length=50)),
                ('build_number', models.CharField(help_text='Build number (es. 123)', max_length=50)),
                ('bundle_id', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Bundle ID deve contenere solo lettere, numeri, punti e trattini', regex='^[a-zA-Z0-9.-]+$')])),
                ('app_file', models.FileField(help_text='File .ipa per iOS o .apk/.aab per Android', upload_to='app_builds/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='app_icons/')),
                ('description', models.TextField(blank=True, help_text='Descrizione delle modifiche')),
                ('release_notes', models.TextField(blank=True, help_text='Note di rilascio')),
                ('min_os_version', models.CharField(blank=True, help_text='Versione minima OS', max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Build disponibile per il download')),
                ('is_beta', models.BooleanField(default=True, help_text='Build beta o release')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Utenti autorizzati al download (lasciare vuoto per tutti)', related_name='allowed_builds', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'bundle_id', 'version', 'build_number')},
            },
        ),
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('app_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='app_distribution.appbuild')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('comment', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app_distribution.appbuild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('app_build', 'user')},
            },
        ),
    ]
