# Generated by Django 5.2.4 on 2025-09-13 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Device Registered'), ('activate', 'Device Activated'), ('deactivate', 'Device Deactivated'), ('compromise_detected', 'Compromise Detected'), ('key_rotation', 'Key Rotation'), ('remote_wipe', 'Remote Wipe'), ('logout', 'User Logout')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='crypto.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'action'], name='devices_dev_device__e3a068_idx'), models.Index(fields=['created_at'], name='devices_dev_created_3dbf2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RemoteWipeCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipe_commands', to='crypto.device')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipe_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'status'], name='devices_rem_device__2401aa_idx'), models.Index(fields=['initiated_by'], name='devices_rem_initiat_05b319_idx'), models.Index(fields=['created_at'], name='devices_rem_created_23e31c_idx')],
            },
        ),
    ]
