name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Server deps
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
      - name: Lint placeholders
        run: echo "TODO: add flake8/dart analyze/eslint"
